---
- hosts: webservers
  name: Pull images and restart containers
  tags:
    - net_worth
  tasks:
  - name: Repull net-worth image
    command: podman pull quay.io/banool/net-worth
  - name: Repull codenames-pictures image
    command: podman pull quay.io/banool/codenames-pictures
  - name: Repull amaranta candles server image
    command: podman pull docker.pkg.github.com/banool/amaranta_candles/amaranta_candles_server
  - name: Repull amaranta candles ui image
    command: podman pull docker.pkg.github.com/banool/amaranta_candles/amaranta_candles_ui
  - name: Repull trapwords image
    command: podman pull quay.io/banool/trapwords
  - name: Repull pants image
    command: podman pull quay.io/banool/pants
  - name: Repull safecycle image
    command: podman pull quay.io/banool/safecycle
  - name: Repull diary-django image
    command: podman pull quay.io/banool/diary-django
  - name: Restart container systemd jobs
    command: systemctl --user restart codenames-pictures net-worth amaranta-candles-ui amaranta-candles-server trapwords pants safecycle diary-django
