---
- hosts: dbservers
  name: Install MySQL 8
  vars:
    user: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
  remote_user: "{{ user }}"
  become: yes
  tasks:
    - name: Install MySQL 8 and Python3 PyMySQL
      dnf:
        name:
          - mysql-server 
          - mysql
          - python3-PyMySQL
        state: latest
    - name: Start and enable MySQL 8
      systemd:
        name: mysqld
        enabled: true
        state: started
    - name: Removes anonymous user account for localhost
      mysql_user:
        name: ''
        host_all: yes
        state: absent
    - name: Create database user with name {{ user }} with all database privileges
      mysql_user:
        name: "{{ user }}"
        password: "{{ password }}"
        priv: '*.*:ALL'
        state: present

