---
- hosts: webservers
  name: Base installation
  tags:
    - base
  tasks:
    - name: Install git
      become: yes
      dnf:
        name:
          - git
    - name: Copy across SSH keys for git purposes
      copy:    
        src: "{{ item }}"
        dest: "/home/{{ unix_user }}/.ssh/"
        owner: "{{ unix_user }}"
        mode: 0600
      with_fileglob:
          - "{{ host_ssh_source }}/id_rsa*"
    - name: Make /var/www directory
      become: yes
      file:
        path: /var/www
        state: directory
        owner: "{{ unix_user }}"
        mode: '0777'
    - name: Put SELinux into Permissive mode
      become: yes
      command: setenforce 0
    - name: Add github.com as known host
      shell: ssh-keyscan -H github.com >> "{{ ansible_env.HOME }}/.ssh/known_hosts"

- hosts: dbservers
  name: Install MySQL 8
  tags:
    - db
  vars:
    user: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
  remote_user: "{{ user }}"
  become: yes
  tasks:
    - name: Install MySQL 8 and Python3 PyMySQL
      dnf:
        name:
          - mysql-server 
          - mysql
          - python3-PyMySQL
        state: latest
    - name: Start and enable MySQL 8
      systemd:
        name: mysqld
        enabled: true
        state: started
    - name: Removes anonymous user account for localhost
      mysql_user:
        name: ''
        host_all: yes
        state: absent
    - name: Create database user with name {{ user }} with all database privileges
      mysql_user:
        name: "{{ user }}"
        password: "{{ password }}"
        priv: '*.*:ALL'
        state: present

- hosts: webservers
  name: Install Net Worth site
  tags:
    - net_worth
  vars:
    unix_user: "{{ unix_user }}"
  tasks:
  - name: Pull net-worth image
    podman_image:
      name: quay.io/banool/net-worth
      tag: latest
  - name: Actually repull net-worth image
    command: podman pull quay.io/banool/net-worth
  - name: Create systemd spec file
    become: yes
    vars:
      allowed_hosts: "{{ net_worth.allowed_hosts }}"
      deployment_mode: "{{ net_worth.deployment_mode }}"
      secret_key: "{{ net_worth.secret_key }}"
      sql_engine: "{{ net_worth.sql_engine }}"
      sql_database: "{{ net_worth.sql_database }}"
      sql_user: "{{ mysql_user }}"
      sql_password: "{{ mysql_password}}"
      sql_host: "{{ net_worth.sql_host}}"
      sql_port: "{{ net_worth.sql_port}}"
      robinhood_username: "{{ net_worth.robinhood_username }}"
      robinhood_password: "{{ net_worth.robinhood_password }}"
      robinhood_2fa_barcode: "{{ net_worth.robinhood_2fa_barcode }}"
      personal_capital_email: "{{ net_worth.personal_capital_email }}"
      personal_capital_password: "{{ net_worth.personal_capital_password }}"
      ui_username: "{{ net_worth.ui_username }}"
      ui_email: "{{ net_worth.ui_email }}"
      ui_password: "{{ net_worth.ui_password }}"
      coinmarketcap_api_key: "{{ net_worth.coinmarketcap_api_key }}"
      internal_port: "{{ net_worth.internal_port }}"
      external_port: "{{ net_worth.external_port }}"
    template:
      src: templates/net-worth.service.j2
      dest: /etc/systemd/system/net-worth.service
      owner: "{{ unix_user }}"
      group: "root"
      mode: '0644'
  - name: Make net worth database in MySQL
    mysql_db:
      name: "{{ net_worth.sql_database }}"
      state: present
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_password }}"
  - name: Start and enable net-worth service
    become: yes
    systemd:
      name: net-worth
      daemon_reload: true
      enabled: true
      state: restarted

- hosts: webservers
  name: Install Codenames Pictures site
  tags:
    - codenames_pictures
  vars:
    unix_user: "{{ unix_user }}"
  tasks:
  - name: Pull codenames-pictures image
    podman_image:
      name: quay.io/banool/codenames-pictures
      tag: latest
  - name: Actually repull codenames-pictures image
    command: podman pull quay.io/banool/codenames-pictures
  - name: Create systemd spec file
    become: yes
    vars:
      internal_port: "{{ codenames_pictures.internal_port }}"
      external_port: "{{ codenames_pictures.external_port }}"
    template:
      src: templates/codenames-pictures.service.j2
      dest: /etc/systemd/system/codenames-pictures.service
      owner: "{{ unix_user }}"
      group: wheel
      mode: '0644'
  - name: Start and enable codenames-pictures service
    become: yes
    systemd:
      name: codenames-pictures
      daemon_reload: true
      enabled: true
      state: restarted

- hosts: webservers
  name: Install dport site
  tags:
    - dport
  vars:
    unix_user: "{{ unix_user }}"
  tasks:
    - git:
        repo: git@github.com:banool/dport-site.git
        dest: /var/www/dport

- hosts: webservers
  name: Install bunkopepi site
  tags:
    - bunkopepi
  tasks:
    - git:
        repo: git@github.com:banool/bunkopepi.git
        dest: /var/www/bunkopepi

- hosts: webservers
  name: Install bunkopepi site
  tags:
    - bunkopepi
  tasks:
    - git:
        repo: git@github.com:banool/bunkopepi.git
        dest: /var/www/bunkopepi

- hosts: webservers
  name: Install internode site
  tags:
    - internode
  tasks:
    - git:
        repo: git@github.com:banool/adport-internode.git
        dest: /var/www/internode

- hosts: webservers
  become: true
  roles:
    - role: nginxinc.nginx
  tags: nginx
  tasks:
    - name: Make /etc/nginx/sites-available
      file:
        path: /etc/nginx/sites-available
        state: directory
        mode: '0755'
    - name: Make symlink for sites-available called sites-enabled
      file:
        src: /etc/nginx/sites-available
        dest: /etc/nginx/sites-enabled
        state: link
    - name: Delete /etc/nginx/conf.d
      file:
        path: /etc/nginx/conf.d
        state: absent
    - name: Use sites-enabled instead of conf.d
      replace:
        path: /etc/nginx/nginx.conf
        regexp: 'include /etc/nginx/conf.d/\*.conf;'
        replace: 'include /etc/nginx/sites-enabled/*;'
    - name: Restart nginx
      systemd:
        name: nginx
        daemon_reload: true
        enabled: true
        state: restarted
  vars:
    nginx_http_template_enable: true
    nginx_http_template:
      dport:
        template_file: http/default.conf.j2
        conf_file_name: dport
        conf_file_location: /etc/nginx/sites-available
        servers:
          server1:
            listen:
              listen_localhost:
                port: 80
            root: /var/www/dport
            server_name: "{{ server_name }} www.{{ server_name }} {{ ip_address }}"
            error_page: /usr/share/nginx/html
            autoindex: false
      net-worth:
        template_file: http/default.conf.j2
        conf_file_name: net-worth
        conf_file_location: /etc/nginx/sites-available
        servers:
          server1:
            listen:
              listen_localhost:
                port: 80
            reverse_proxy:
              locations:
                backend:
                  location: /
                  proxy_pass: "http://127.0.0.1:{{ net_worth.internal_port }}"
            server_name: "net-worth.{{ server_name }}"
            error_page: /usr/share/nginx/html
            autoindex: false
      codenames-pictures:
        template_file: http/default.conf.j2
        conf_file_name: codenames-pictures
        conf_file_location: /etc/nginx/sites-available
        servers:
          server1:
            listen:
              listen_localhost:
                port: 80
            reverse_proxy:
              locations:
                backend:
                  location: /
                  proxy_pass: "http://127.0.0.1:{{ codenames_pictures.internal_port}}"
            server_name: "codenames-pictures.{{ server_name }} codenames.{{ server_name }}"
            error_page: /usr/share/nginx/html
            autoindex: false


- hosts: webservers
  name: Setup https
  tags:
    - https
  tasks:
    - name: Get public IP of this host
      command: "dig -4 @resolver1.opendns.com ANY myip.opendns.com +short"
      register: public_ip
    - name: Get IP of domain
      command: "dig -4 +short {{ server_name }}"
      register: domain_ip
    - name: Print debug success when both IPs are the same
      debug: 
        msg: "Public IP: {{ public_ip.stdout }} Domain IP: {{ domain_ip.stdout }}" 
    - name: Confirm both IPs the same
      fail:
        msg: The public IP of the host and the IP of the domain are not the same
      when: public_ip.stdout != domain_ip.stdout
    - name: Print debug success when both IPs are the same
      debug: 
        msg: The public IP of the host and the IP of the domain are the same, hopefully this means your DNS records are correct. Also think about NAT. Proceeding with https
    - name: Get certbot
      become: yes
      command: wget https://dl.eff.org/certbot-auto && mv certbot-auto /usr/local/bin/certbot-auto && chown root /usr/local/bin/certbot-auto && chmod 0755 /usr/local/bin/certbot-auto
    - name: Run certbot
      become: yes
      command: /usr/local/bin/certbot-auto --nginx
    - name: Put autorenew in crontab
      cron:
        name: "autorenew certs with cerbot"
        minute: "0"
        hour: "2"
        job: "/usr/local/bin/certbot-auto renew -q"


# TODO
# Nginx
# All other sites
# #https
# Crons
# Deluge
# Plex
# External HDD mounts
# Turning off the screen
# History for net worth
# certbot
